services:
  - type: web
    name: txt-to-video-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        value: "25438884"
      - key: API_HASH
        value: "5959aaa61e1aba458d1b1dd53048ca3a"
      - key: BOT_TOKEN
        value: "8157792832:AAH2fIunSMdadgR6XifANiO9IWRVz-1N6dc"
